---
- name: fix rc file permisson
  file: >
    dest={{user_home}}/{{item}} mode="u+x" recurse=true
  with_items:
    - .bashrc.d
    - .profile.d
  tags:
    - shell

- name: system bashrc source bash.aliases
  become: true
  lineinfile:
    dest: "{{system_bashrc}}"
    line: >
      [[ -r /etc/bash.aliases ]] && . /etc/bash.aliases
    state: present
  tags:
    - shell
