- name: install spacemacs
  git:
    repo: https://github.com/syl20bnr/spacemacs
    dest: "{{user_home}}/.emacs.d"

- name: install spacemacs config
  git:
    repo: git@github.com:wenxin-wang/.spacemacs.d
    dest: "{{user_home}}/.spacemacs.d"
    accept_hostkey: true
