---
- name: install packages
  become: true
  package: "name={{item}} state=latest"
  with_items: '{{packages}}'
  tags:
    - packages

- include: common.yml
  tags:
    - packages

- include: "{{env}}.yml"
  tags:
    - packages
