---
- name: setup repo for yaourt
  become: true
  ini_file:
    dest: /etc/pacman.conf
    section: archlinuxfr
    option: "{{item.key}}"
    value: "{{item.value}}"
    state: present
  with_dict:
    SigLevel: Never
    Server: http://repo.archlinux.fr/$arch
  tags:
    - packages

- name: install packages
  become: true
  package: "name={{item}} state=latest"
  with_items: '{{packages}}'
  tags:
    - packages

# - name: install aur packages
#   command: >
#     yaourt -S --noconfirm {{aur_packages | join(" ")}}
#   tags:
#     - packages
#     - aur

- include: common.yml
  tags:
    - packages

- include: "{{env}}.yml"
  tags:
    - packages
