---
- name: enable and start lightdm
  become: true
  service: name=lightdm enabled=true state=started
  tags:
    - X

- name: lightdm settings
  become: true
  ini_file:
    dest: "/etc/lightdm/lightdm.conf"
    section: "Seat:*"
    option: display-setup-script
    value: /usr/local/bin/load_xmodmaprc
    state: present
  tags:
    - X

- name: install base16 themes
  git:
    repo: https://github.com/chriskempson/base16-xresources.git
    dest: "{{user_home}}/.Xresources.d/base16-themes"
  tags:
    - X
