---
- name: enable and start lightdm
  become: true
  service: name=lightdm enabled=true state=started
  tags:
    - X

- name: lightdm settings
  become: true
  ini_file:
    dest: "/etc/lightdm/lightdm.conf"
    section: "Seat:*"
    option: "{{item.key}}"
    value: "{{item.value}}"
    state: present
  with_dict:
    display-setup-script: /usr/local/bin/xkb-custom
    greeter-session: lightdm-webkit2-greeter
  tags:
    - X

- name: install base16 themes
  git:
    repo: https://github.com/chriskempson/base16-xresources.git
    dest: "{{user_home}}/.Xresources.d/base16-themes"
    depth: 1
  tags:
    - X

- name: enable user xsession
  file:
    dest: "{{user_home}}/.xsession"
    mode: "u+x"
  tags:
    - X
