---
- name: generate host file
  become: true
  template:
    src: "{{instance_dir}}/net/hosts.jinja2"
    dest: /etc/hosts
  tags:
    - network

- name: enable and start shadowsocks
  become: true
  service: >
    name=shadowsocks-libev@{{item}} enabled=true state=started
  with_items:
    - v4
    - v6
  tags:
    - network
