---
- name: generate host file
  become: true
  template:
    src: "{{instance_dir}}/net/hosts.jinja2"
    dest: /etc/hosts
  tags:
    - network

#- name: copy shadowsocks deb
#  become: true
#  copy:
#    src: "{{instance_dir}}/net/shadowsocks-libev.deb"
#    dest: /tmp/
#  tags:
#    - network
#
#- name: install shadowsocks
#  become: true
#  apt: deb=/tmp/shadowsocks-libev.deb
#  tags:
#    - network

- name: enable and start shadowsocks
  become: true
  service: >
    name=shadowsocks-libev@{{item}} enabled=true state=started
  with_items:
    - v4
    - v6
  tags:
    - network

- name: enable NetworkManager
  become: true
  service: >
    name=NetworkManager enabled=true
  tags:
    - network
